OPENAI_API_KEY = "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"

SMTP_EMAIL = "intelligentsystems512@gmail.com"
SMTP_PASSWORD = "ztetdzmejhxjjcfi"
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 465